report_reasons = [
    "Report a photo",
    "Inappropriate message or profile",
    "In person harm or unsafe situation",
    "Scam, fake account, or selling something",
    "Under age",
    "Other"
]

diet_update = [
    "halal",
    "kosher",
    "anything",
    "vegan",
    "vegetarian"
]

diets = [
    "anything",
    "halal",
    "kosher",
    "mostly anything",
    "mostly halal",
    "mostly kosher",
    "mostly other",
    "mostly vegan",
    "mostly vegetarian",
    "nan",
    "other",
    "strictly anything",
    "strictly halal",
    "strictly kosher",
    "strictly other",
    "strictly vegan",
    "strictly vegetarian",
    "vegan",
    "vegetarian",
]


drinks = [
    "desperately",
    "nan",
    "not at all",
    "often",
    "rarely",
    "socially",
    "very often",
]

body_types = [
    "fit",
    "a little extra",
    "thin",
    "athletic",
    "average",
    "full figured",
    "skinny",
    "curvy",
    "used up",
    "overweight",
    "nan",
]


smokes = ["nan", "no", "sometimes", "trying to quit", "when drinking", "yes"]

ethnicities_update = [
    "asian",
    "black",
    "white",
    "indian",
    "hispanic / latin",
    "pacific islander",
    "native american",
    "nan",
    "middle eastern"
]

ethnicities = [
    "asian",
    "asian, black",
    "asian, black, hispanic / latin",
    "asian, black, hispanic / latin, other",
    "asian, black, hispanic / latin, white",
    "asian, black, hispanic / latin, white, other",
    "asian, black, indian",
    "asian, black, indian, hispanic / latin, other",
    "asian, black, native american",
    "asian, black, native american, hispanic / latin",
    "asian, black, native american, hispanic / latin, white",
    "asian, black, native american, indian",
    "asian, black, native american, indian, hispanic / latin, white, other",
    "asian, black, native american, indian, pacific islander, hispanic / latin",
    "asian, black, native american, indian, pacific islander, white",
    "asian, black, native american, other",
    "asian, black, native american, pacific islander",
    "asian, black, native american, pacific islander, other",
    "asian, black, native american, pacific islander, white",
    "asian, black, native american, pacific islander, white, other",
    "asian, black, native american, white",
    "asian, black, native american, white, other",
    "asian, black, other",
    "asian, black, pacific islander",
    "asian, black, pacific islander, hispanic / latin",
    "asian, black, pacific islander, hispanic / latin, white",
    "asian, black, pacific islander, other",
    "asian, black, pacific islander, white",
    "asian, black, pacific islander, white, other",
    "asian, black, white",
    "asian, black, white, other",
    "asian, hispanic / latin",
    "asian, hispanic / latin, other",
    "asian, hispanic / latin, white",
    "asian, hispanic / latin, white, other",
    "asian, indian",
    "asian, indian, hispanic / latin",
    "asian, indian, hispanic / latin, other",
    "asian, indian, hispanic / latin, white",
    "asian, indian, other",
    "asian, indian, pacific islander",
    "asian, indian, pacific islander, hispanic / latin, white, other",
    "asian, indian, pacific islander, other",
    "asian, indian, white",
    "asian, indian, white, other",
    "asian, middle eastern",
    "asian, middle eastern, black",
    "asian, middle eastern, black, indian, pacific islander, hispanic / latin, white",
    "asian, middle eastern, black, native american, hispanic / latin, white",
    "asian, middle eastern, black, native american, indian, pacific islander, hispanic / latin",
    "asian, middle eastern, black, native american, indian, pacific islander, hispanic / latin, other",
    "asian, middle eastern, black, native american, indian, pacific islander, hispanic / latin, white",
    "asian, middle eastern, black, native american, indian, pacific islander, hispanic / latin, white, other",
    "asian, middle eastern, black, native american, indian, pacific islander, white",
    "asian, middle eastern, black, native american, pacific islander, hispanic / latin, white, other",
    "asian, middle eastern, black, pacific islander",
    "asian, middle eastern, black, pacific islander, hispanic / latin",
    "asian, middle eastern, black, pacific islander, hispanic / latin, white",
    "asian, middle eastern, black, white, other",
    "asian, middle eastern, hispanic / latin",
    "asian, middle eastern, hispanic / latin, white",
    "asian, middle eastern, hispanic / latin, white, other",
    "asian, middle eastern, indian",
    "asian, middle eastern, indian, hispanic / latin",
    "asian, middle eastern, indian, hispanic / latin, white, other",
    "asian, middle eastern, indian, other",
    "asian, middle eastern, native american, hispanic / latin, white",
    "asian, middle eastern, native american, indian, pacific islander, hispanic / latin, white",
    "asian, middle eastern, native american, pacific islander, hispanic / latin, white, other",
    "asian, middle eastern, native american, pacific islander, other",
    "asian, middle eastern, native american, pacific islander, white, other",
    "asian, middle eastern, other",
    "asian, middle eastern, white",
    "asian, middle eastern, white, other",
    "asian, native american",
    "asian, native american, hispanic / latin",
    "asian, native american, hispanic / latin, other",
    "asian, native american, hispanic / latin, white",
    "asian, native american, hispanic / latin, white, other",
    "asian, native american, indian, pacific islander, hispanic / latin, white",
    "asian, native american, indian, pacific islander, hispanic / latin, white, other",
    "asian, native american, other",
    "asian, native american, pacific islander",
    "asian, native american, pacific islander, hispanic / latin, white",
    "asian, native american, pacific islander, hispanic / latin, white, other",
    "asian, native american, pacific islander, white",
    "asian, native american, pacific islander, white, other",
    "asian, native american, white",
    "asian, native american, white, other",
    "asian, other",
    "asian, pacific islander",
    "asian, pacific islander, hispanic / latin",
    "asian, pacific islander, hispanic / latin, other",
    "asian, pacific islander, hispanic / latin, white",
    "asian, pacific islander, hispanic / latin, white, other",
    "asian, pacific islander, other",
    "asian, pacific islander, white",
    "asian, pacific islander, white, other",
    "asian, white",
    "asian, white, other",
    "black",
    "black, hispanic / latin",
    "black, hispanic / latin, other",
    "black, hispanic / latin, white",
    "black, hispanic / latin, white, other",
    "black, indian",
    "black, indian, hispanic / latin",
    "black, indian, hispanic / latin, white",
    "black, indian, other",
    "black, indian, white",
    "black, indian, white, other",
    "black, native american",
    "black, native american, hispanic / latin",
    "black, native american, hispanic / latin, other",
    "black, native american, hispanic / latin, white",
    "black, native american, hispanic / latin, white, other",
    "black, native american, indian",
    "black, native american, indian, hispanic / latin, white, other",
    "black, native american, indian, other",
    "black, native american, indian, pacific islander",
    "black, native american, indian, pacific islander, hispanic / latin",
    "black, native american, indian, white",
    "black, native american, indian, white, other",
    "black, native american, other",
    "black, native american, pacific islander",
    "black, native american, pacific islander, hispanic / latin",
    "black, native american, pacific islander, hispanic / latin, white",
    "black, native american, pacific islander, hispanic / latin, white, other",
    "black, native american, pacific islander, other",
    "black, native american, pacific islander, white",
    "black, native american, pacific islander, white, other",
    "black, native american, white",
    "black, native american, white, other",
    "black, other",
    "black, pacific islander",
    "black, pacific islander, hispanic / latin",
    "black, pacific islander, other",
    "black, pacific islander, white",
    "black, white",
    "black, white, other",
    "hispanic / latin",
    "hispanic / latin, other",
    "hispanic / latin, white",
    "hispanic / latin, white, other",
    "indian",
    "indian, hispanic / latin",
    "indian, hispanic / latin, other",
    "indian, hispanic / latin, white",
    "indian, hispanic / latin, white, other",
    "indian, other",
    "indian, pacific islander",
    "indian, pacific islander, hispanic / latin, white",
    "indian, white",
    "indian, white, other",
    "middle eastern",
    "middle eastern, black",
    "middle eastern, black, hispanic / latin",
    "middle eastern, black, indian, pacific islander, hispanic / latin, white",
    "middle eastern, black, native american, hispanic / latin, white",
    "middle eastern, black, native american, indian",
    "middle eastern, black, native american, indian, hispanic / latin, white",
    "middle eastern, black, native american, indian, pacific islander, hispanic / latin, white",
    "middle eastern, black, native american, indian, pacific islander, hispanic / latin, white, other",
    "middle eastern, black, native american, indian, white, other",
    "middle eastern, black, native american, white",
    "middle eastern, black, native american, white, other",
    "middle eastern, black, other",
    "middle eastern, black, pacific islander, white",
    "middle eastern, black, white",
    "middle eastern, hispanic / latin",
    "middle eastern, hispanic / latin, other",
    "middle eastern, hispanic / latin, white",
    "middle eastern, hispanic / latin, white, other",
    "middle eastern, indian",
    "middle eastern, indian, other",
    "middle eastern, indian, white",
    "middle eastern, indian, white, other",
    "middle eastern, native american",
    "middle eastern, native american, hispanic / latin",
    "middle eastern, native american, hispanic / latin, white",
    "middle eastern, native american, hispanic / latin, white, other",
    "middle eastern, native american, white",
    "middle eastern, native american, white, other",
    "middle eastern, other",
    "middle eastern, pacific islander",
    "middle eastern, pacific islander, hispanic / latin",
    "middle eastern, pacific islander, other",
    "middle eastern, white",
    "middle eastern, white, other",
    "nan",
    "native american",
    "native american, hispanic / latin",
    "native american, hispanic / latin, other",
    "native american, hispanic / latin, white",
    "native american, hispanic / latin, white, other",
    "native american, indian",
    "native american, indian, pacific islander, hispanic / latin",
    "native american, indian, white",
    "native american, other",
    "native american, pacific islander",
    "native american, pacific islander, hispanic / latin",
    "native american, pacific islander, hispanic / latin, white",
    "native american, pacific islander, hispanic / latin, white, other",
    "native american, pacific islander, white",
    "native american, pacific islander, white, other",
    "native american, white",
    "native american, white, other",
    "other",
    "pacific islander",
    "pacific islander, hispanic / latin",
    "pacific islander, hispanic / latin, other",
    "pacific islander, hispanic / latin, white",
    "pacific islander, hispanic / latin, white, other",
    "pacific islander, other",
    "pacific islander, white",
    "pacific islander, white, other",
    "white",
    "white, other",
]



educations_update = [
    "college",
    "dropped out",
    "master",
    "phd"
]

educations = [
    "college/university",
    "dropped out of college/university",
    "dropped out of high school",
    "dropped out of law school",
    "dropped out of masters program",
    "dropped out of med school",
    "dropped out of ph.d program",
    "dropped out of space camp",
    "dropped out of two-year college",
    "graduated from college/university",
    "graduated from high school",
    "graduated from law school",
    "graduated from masters program",
    "graduated from med school",
    "graduated from ph.d program",
    "graduated from space camp",
    "graduated from two-year college",
    "high school",
    "law school",
    "masters program",
    "med school",
    "nan",
    "ph.d program",
    "space camp",
    "two-year college",
    "working on college/university",
    "working on high school",
    "working on law school",
    "working on masters program",
    "working on med school",
    "working on ph.d program",
    "working on space camp",
    "working on two-year college",
]
jobs = [
    "artistic / musical / writer",
    "banking / financial / real estate",
    "clerical / administrative",
    "computer / hardware / software",
    "construction / craftsmanship",
    "education / academia",
    "entertainment / media",
    "executive / management",
    "hospitality / travel",
    "law / legal services",
    "medicine / health",
    "military",
    "nan",
    "other",
    "political / government",
    "rather not say",
    "retired",
    "sales / marketing / biz dev",
    "science / tech / engineering",
    "student",
    "transportation",
    "unemployed",
]

locations_update = [
    "nan",
    "california",
    "north carolina",
    "new york",
    "georgia",
    "texas",
    "washington",
    "illinois",
    "montana",
    "idaho",
    "ohio"
]
locations = [
    "alameda, california",
    "albany, california",
    "amsterdam, netherlands",
    "arcadia, california",
    "asheville, north carolina",
    "ashland, california",
    "astoria, new york",
    "atherton, california",
    "atlanta, georgia",
    "austin, texas",
    "bayshore, california",
    "bellingham, washington",
    "bellwood, illinois",
    "belmont, california",
    "belvedere tiburon, california",
    "benicia, california",
    "berkeley, california",
    "billings, montana",
    "boise, idaho",
    "bolinas, california",
    "bonaduz, switzerland",
    "boston, massachusetts",
    "boulder, colorado",
    "brea, california",
    "brisbane, california",
    "brooklyn, new york",
    "burlingame, california",
    "cambridge, massachusetts",
    "campbell, california",
    "canyon country, california",
    "canyon, california",
    "castro valley, california",
    "chicago, illinois",
    "chico, california",
    "cincinnati, ohio",
    "colma, california",
    "columbus, ohio",
    "concord, california",
    "cork, ireland",
    "corte madera, california",
    "costa mesa, california",
    "crockett, california",
    "crowley, texas",
    "daly city, california",
    "denver, colorado",
    "east palo alto, california",
    "edinburgh, united kingdom",
    "el cerrito, california",
    "el granada, california",
    "el sobrante, california",
    "emeryville, california",
    "fairfax, california",
    "fayetteville, west virginia",
    "forest knolls, california",
    "fort lauderdale, florida",
    "foster city, california",
    "freedom, california",
    "fremont, california",
    "glencove, california",
    "grand rapids, michigan",
    "granite bay, california",
    "green brae, california",
    "guadalajara, mexico",
    "hacienda heights, california",
    "half moon bay, california",
    "hayward, california",
    "hercules, california",
    "hilarita, california",
    "hillsborough, california",
    "honolulu, hawaii",
    "irvine, california",
    "isla vista, california",
    "islip terrace, new york",
    "jackson, mississippi",
    "kansas city, missouri",
    "kassel, germany",
    "kensington, california",
    "kentfield, california",
    "kula, hawaii",
    "lafayette, california",
    "lagunitas, california",
    "lake orion, michigan",
    "larkspur, california",
    "las vegas, nevada",
    "leander, texas",
    "livingston, california",
    "london, united kingdom",
    "long beach, california",
    "long beach, new york",
    "longwood, florida",
    "los angeles, california",
    "los gatos, california",
    "madrid, spain",
    "magalia, california",
    "marin city, california",
    "martinez, california",
    "menlo park, california",
    "miami, florida",
    "mill valley, california",
    "millbrae, california",
    "milpitas, california",
    "milwaukee, wisconsin",
    "minneapolis, minnesota",
    "modesto, california",
    "montara, california",
    "moraga, california",
    "moss beach, california",
    "mountain view, california",
    "muir beach, california",
    "murfreesboro, tennessee",
    "napa, california",
    "nevada city, california",
    "new orleans, louisiana",
    "new york, new york",
    "nha trang, vietnam",
    "nicasio, california",
    "north hollywood, california",
    "novato, california",
    "oakland, california",
    "oakley, california",
    "oceanview, california",
    "olema, california",
    "orange, california",
    "orinda, california",
    "ozone park, new york",
    "pacheco, california",
    "pacifica, california",
    "palo alto, california",
    "pasadena, california",
    "peoria, illinois",
    "petaluma, california",
    "philadelphia, pennsylvania",
    "phoenix, arizona",
    "piedmont, california",
    "pinole, california",
    "pleasant hill, california",
    "point richmond, california",
    "port costa, california",
    "portland, oregon",
    "providence, rhode island",
    "redwood city, california",
    "redwood shores, california",
    "richmond, california",
    "riverside, california",
    "rochester, michigan",
    "rodeo, california",
    "rohnert park, california",
    "ross, california",
    "sacramento, california",
    "salt lake city, utah",
    "san anselmo, california",
    "san antonio, texas",
    "san bruno, california",
    "san carlos, california",
    "san diego, california",
    "san francisco, california",
    "san geronimo, california",
    "san jose, california",
    "san leandro, california",
    "san lorenzo, california",
    "san luis obispo, california",
    "san mateo, california",
    "san pablo, california",
    "san quentin, california",
    "san rafael, california",
    "santa ana, california",
    "santa clara, california",
    "santa cruz, california",
    "santa monica, california",
    "santa rosa, california",
    "sausalito, california",
    "seaside, california",
    "seattle, washington",
    "south lake tahoe, california",
    "south orange, new jersey",
    "south san francisco, california",
    "south wellfleet, massachusetts",
    "stanford, california",
    "stinson beach, california",
    "stockton, california",
    "stratford, connecticut",
    "studio city, california",
    "sunnyvale, california",
    "taunton, massachusetts",
    "tiburon, california",
    "tucson, arizona",
    "union city, california",
    "utica, michigan",
    "vacaville, california",
    "vallejo, california",
    "vancouver, british columbia, canada",
    "walnut creek, california",
    "washington, district of columbia",
    "waterford, california",
    "west oakland, california",
    "westlake, california",
    "woodacre, california",
    "woodbridge, virginia",
    "woodside, california",
]

pets = [
    "dislikes cats",
    "dislikes dogs",
    "dislikes dogs and dislikes cats",
    "dislikes dogs and has cats",
    "dislikes dogs and likes cats",
    "has cats",
    "has dogs",
    "has dogs and dislikes cats",
    "has dogs and has cats",
    "has dogs and likes cats",
    "likes cats",
    "likes dogs",
    "likes dogs and dislikes cats",
    "likes dogs and has cats",
    "likes dogs and likes cats",
    "nan",
]

pets_update = [
    "cats",
    "dogs",
    "cats and dogs",
    "dislike dogs",
    "dislike cats",
    "dislike dogs and cats"
    "none"
]
children_update = [
    "want kids",
    "nan",
    "do not want kids",
]
children = [
    "doesn't have kids",
    "doesn't have kids, and doesn't want any",
    "doesn't have kids, but might want them",
    "doesn't have kids, but wants them",
    "doesn't want kids",
    "has a kid",
    "has a kid, and might want more",
    "has a kid, and wants more",
    "has a kid, but doesn't want more",
    "has kids",
    "has kids, and might want more",
    "has kids, and wants more",
    "has kids, but doesn't want more",
    "might want kids",
    "nan",
    "wants kids",
]


religions_update = [
    "agnosticism",
    "atheism",
    "buddhism",
    "catholicism",
    "christianity",
    "hinduism",
    "islam",
    "judaism",
    "nan",
]
religions = [
    "agnosticism",
    "agnosticism and laughing about it",
    "agnosticism and somewhat serious about it",
    "agnosticism and very serious about it",
    "agnosticism but not too serious about it",
    "atheism",
    "atheism and laughing about it",
    "atheism and somewhat serious about it",
    "atheism and very serious about it",
    "atheism but not too serious about it",
    "buddhism",
    "buddhism and laughing about it",
    "buddhism and somewhat serious about it",
    "buddhism and very serious about it",
    "buddhism but not too serious about it",
    "catholicism",
    "catholicism and laughing about it",
    "catholicism and somewhat serious about it",
    "catholicism and very serious about it",
    "catholicism but not too serious about it",
    "christianity",
    "christianity and laughing about it",
    "christianity and somewhat serious about it",
    "christianity and very serious about it",
    "christianity but not too serious about it",
    "hinduism",
    "hinduism and laughing about it",
    "hinduism and somewhat serious about it",
    "hinduism and very serious about it",
    "hinduism but not too serious about it",
    "islam",
    "islam and laughing about it",
    "islam and somewhat serious about it",
    "islam and very serious about it",
    "islam but not too serious about it",
    "judaism",
    "judaism and laughing about it",
    "judaism and somewhat serious about it",
    "judaism and very serious about it",
    "judaism but not too serious about it",
    "nan",
    "other",
    "other and laughing about it",
    "other and somewhat serious about it",
    "other and very serious about it",
    "other but not too serious about it",
]
languages_update = [
    "english",
    "greek",
    "c++",
    "french",
    "chinese",
    "spanish",
    "italian",
    "german",
    "hindi",
    "latin",
    "nan",
]
languages = [
    "nan",
    "english (fluently), greek (poorly), c++ (okay), sign language (poorly), tagalog (poorly)",
    "english (fluently), urdu (fluently), french (poorly)",
    "english, french, c++, spanish (poorly), german (poorly)",
    "english (fluently), chinese (fluently), c++ (fluently), lisp (fluently)",
    "english (fluently), yiddish (poorly), afrikaans (poorly), c++ (poorly), chinese (poorly)",
    "english (fluently), french (okay), italian (fluently), spanish (okay)",
    "english, c++ (okay), lisp (okay)",
    "english, english (fluently), german (okay), hindi (fluently), c++ (fluently)",
    "english (fluently), spanish (poorly), latin (poorly), ancient greek (poorly)",
    "english (fluently), c++ (okay), german (fluently)",
    "english (fluently), dutch (okay), german (fluently)",
    "english (fluently), french (fluently), sign language (fluently)",
    "english (fluently), spanish (fluently), russian (okay), tagalog (poorly), arabic (okay)",
    "english (okay), italian (okay), portuguese (poorly), swahili (fluently)",
    "english (fluently), chinese (fluently), german (poorly)",
    "english (fluently), french (okay), spanish (okay), german (okay), esperanto (poorly)",
    "english (fluently), german (fluently), latvian (fluently), spanish (poorly)",
    "english, german (poorly), c++, swedish (poorly)",
    "english (fluently), spanish (okay), tamil (poorly)",
    "english, hindi (poorly), chinese (poorly)",
    "english (fluently), dutch (fluently), german (okay)",
    "english (fluently), dutch (poorly), german (poorly), sign language (poorly)",
    "english, spanish, german, french, portuguese",
    "english, german, polish",
    "english (fluently), french (fluently), urdu (fluently), hindi (fluently), japanese (okay)",
    "english (fluently), spanish, japanese, farsi",
    "english (fluently), portuguese (fluently), german (okay), spanish (okay), french (poorly)",
    "english (fluently), japanese (okay), spanish (fluently)",
    "english (fluently), chinese (okay), french (poorly)",
    "english (fluently), french (okay), latvian (okay), russian (fluently)",
    "english (fluently), vietnamese (okay), japanese (poorly)",
    "english (fluently), spanish (okay), hebrew (poorly), russian (poorly)",
    "english, german (fluently), french (okay), spanish (poorly)",
    "english, persian, arabic, german",
    "english (fluently), french (poorly), greek (okay), latin (poorly)",
    "english (fluently), french (poorly), other (okay)",
    "english, spanish, thai, chinese",
    "english (fluently), french (okay), afrikaans (fluently)",
    "english, spanish (poorly), farsi (poorly)",
    "english (fluently), turkish (fluently), korean (okay), c++ (fluently)",
    "english (fluently), c++ (okay), spanish (poorly)",
    "english, other (fluently), german (okay)",
    "english (fluently), indonesian (fluently), other (fluently), japanese (poorly), italian (poorly)",
    "english (fluently), french (poorly), spanish (okay), thai (poorly)",
    "english (fluently), vietnamese (okay), spanish (poorly), japanese (poorly)",
    "english (fluently), yiddish (okay), ilongo (poorly)",
    "english (fluently), c++ (fluently), lisp (poorly), italian (poorly)",
    "english, vietnamese (fluently), khmer (poorly)",
    "english (poorly), german (poorly)",
    "english (fluently), sign language (poorly), esperanto (poorly)",
    "english, other, other, other",
    "english (fluently), german (poorly), japanese (poorly)",
    "english (fluently), japanese (okay), spanish (okay), french (poorly), c++ (okay)",
    "english (fluently), german (fluently), greek (poorly), spanish (poorly)",
    "english (fluently), japanese (poorly), tagalog (poorly)",
    "english (fluently), french (poorly), urdu (fluently), other (fluently), other (fluently)",
    "english, indonesian, portuguese",
    "english (fluently), french (okay), malay (okay)",
    "english (fluently), french (okay), chinese (okay), spanish (poorly)",
    "english (fluently), chinese (fluently), korean (fluently), japanese (okay)",
    "english (fluently), spanish (fluently), italian (okay), french (poorly)",
    "english, french, swedish (poorly)",
    "english (fluently), hebrew (fluently), yiddish (poorly), spanish (poorly)",
    "english, german (fluently), spanish (fluently), french (okay), portuguese (poorly)",
    "english (fluently), japanese (fluently), spanish (fluently), italian (okay)",
    "english (fluently), italian (poorly), sign language (poorly)",
    "english (fluently), lisp (poorly), spanish (poorly), chinese (poorly), german (poorly)",
    "english (fluently), french (poorly), russian (poorly)",
    "english, bengali, yiddish",
    "english (fluently), lisp (okay)",
    "english (fluently), spanish (okay), sign language (poorly), other",
    "english (fluently), japanese (poorly), lisp (okay)",
    "english (fluently), french (poorly), tagalog (poorly), c++ (fluently)",
    "english (fluently), ancient greek (poorly), other",
    "english (fluently), other (fluently), hindi (fluently), urdu (okay)",
    "english (fluently), spanish (okay), french (okay), german (poorly)",
    "english (fluently), russian (poorly), spanish (poorly), japanese (poorly)",
    "english (fluently), spanish (okay), croatian (okay), serbian (poorly), sign language (okay)",
    "english (fluently), spanish (poorly), esperanto",
    "english (fluently), hebrew (fluently), spanish (okay), latin (poorly), c++ (fluently)",
    "english (okay), spanish (poorly), german (poorly), arabic (poorly)",
    "english (fluently), russian (fluently), spanish (okay), lithuanian (fluently)",
    "english (fluently), arabic (okay), french (okay), german (poorly), spanish (poorly)",
    "english (fluently), spanish (okay), german (poorly)",
    "english (poorly), spanish (poorly), japanese (poorly), portuguese (poorly)",
    "english (fluently), french (fluently), german (fluently), spanish (okay)",
    "english (fluently), spanish (okay), c++ (fluently), welsh (poorly)",
    "english (fluently), arabic (fluently), greek (okay), french (okay)",
    "english, spanish (poorly), norwegian (poorly), portuguese (poorly)",
    "english (fluently), swedish (poorly), spanish (poorly)",
    "english (fluently), spanish (okay), french (okay), german (okay), swedish (poorly)",
    "english (fluently), german (fluently), swedish (poorly), c++ (fluently), norwegian (poorly)",
    "english (fluently), spanish (poorly), hebrew (poorly), russian (poorly)",
    "english (fluently), french (poorly), yiddish (poorly), lisp (poorly)",
    "english (fluently), farsi (okay), arabic (poorly), spanish (poorly)",
    "english (fluently), japanese (poorly), sign language (poorly)",
    "english (fluently), vietnamese (fluently), french (poorly), dutch (poorly)",
    "english, hebrew, spanish (poorly), c++ (poorly)",
    "english (fluently), thai (okay), sign language (poorly), spanish (poorly)",
    "english (fluently), hindi (poorly), french (poorly), other (fluently)",
    "english (fluently), french (fluently), german (poorly), japanese (poorly)",
    "english (fluently), greek (fluently), spanish (fluently)",
    "english, german (okay), french (okay)",
    "english (fluently), russian (fluently), hebrew (okay)",
    "english, hungarian (fluently), french (okay)",
    "english (fluently), arabic (poorly), hebrew (okay), spanish (okay)",
    "english (fluently), italian (poorly), spanish (poorly), irish (poorly)",
    "english, german (fluently), spanish (okay), french (okay), sanskrit (poorly)",
    "english (fluently), c++ (fluently), chinese (fluently), japanese (poorly)",
    "english (fluently), chinese (fluently), french (poorly), portuguese (poorly)",
    "english (fluently), spanish (fluently), farsi (poorly), tagalog (poorly)",
    "english (fluently), spanish (fluently), italian (okay), latin (okay)",
    "english (fluently), spanish (okay), swedish (poorly), german (poorly), japanese (poorly)",
    "english (fluently), spanish (okay), farsi (poorly)",
    "english (fluently), french (fluently), greek (fluently), spanish (poorly), japanese (poorly)",
    "english (fluently), chinese (okay), spanish (poorly), yiddish (poorly)",
    "english (okay), spanish (okay), sign language (okay), russian (poorly)",
    "english (fluently), sign language (okay), spanish (poorly), german (poorly)",
    "english (fluently), japanese (okay), french (okay), hawaiian (okay)",
    "english (fluently), french (fluently), swahili (poorly)",
    "english (fluently), italian (okay), french (okay), swedish (poorly)",
    "english, dutch, spanish",
    "english (fluently), hebrew (poorly), german (poorly)",
    "english (fluently), spanish (fluently), portuguese (okay), hindi (poorly)",
    "english (fluently), german (okay), spanish (okay), italian (poorly)",
    "english (fluently), french (fluently), japanese (okay), chinese (poorly)",
    "english (fluently), korean (fluently), spanish (okay)",
    "english (fluently), spanish (fluently), german (fluently), italian (okay)",
    "english (fluently), russian (fluently), spanish (poorly)",
    "english (okay), afrikaans (fluently)",
    "english (fluently), russian (okay), french (fluently)",
    "english (fluently), spanish (fluently), german (fluently), italian (poorly), chinese (poorly)",
    "english, hindi (fluently), urdu (fluently)",
    "english (fluently), hebrew (poorly), russian (okay)",
    "english, thai (poorly), french (poorly)",
    "english (fluently), tagalog (poorly), spanish (poorly), arabic (poorly)",
    "english (fluently), russian (fluently), spanish (poorly), c++ (okay)",
    "english (fluently), spanish (fluently), french (poorly), portuguese (okay), italian (poorly)",
    "english (okay), spanish, portuguese (fluently)",
    "english, hebrew (fluently), french (okay)",
    "english (fluently), french (fluently), german (okay), japanese (poorly)",
    "english (fluently), chinese (poorly), french (fluently), japanese (fluently), italian (poorly)",
    "english (fluently), french (poorly), korean (okay)",
    "english (fluently), belarusan (okay), rotuman (fluently), tagalog (poorly), hawaiian (poorly)",
    "english (fluently), c++ (fluently), spanish (okay), turkish (fluently)",
    "english (fluently), chinese (fluently), spanish (okay), japanese (okay)",
    "english, dutch, polish",
    "english, italian (fluently), spanish (okay), swedish (poorly)",
    "english (fluently), latin (poorly), ancient greek (poorly), sign language (poorly)",
    "english (fluently), spanish (fluently), french (fluently)",
    "english, french (okay), spanish (poorly), hebrew (poorly)",
    "english, sanskrit (poorly), german (poorly), spanish (poorly)",
    "english (fluently), swahili (fluently), urdu (fluently), french (okay), portuguese (poorly)",
    "english (fluently), french (poorly), latin (poorly), esperanto (poorly)",
    "english (fluently), japanese (okay), thai (okay)",
    "english (fluently), spanish (okay), french (poorly), swedish (poorly)",
    "english (fluently), tagalog (fluently), spanish (poorly)",
    "english, french (okay), spanish (okay)",
    "english (fluently), polish (fluently), french (poorly)",
    "english (fluently), hindi (fluently), lisp (fluently)",
    "english (fluently), spanish (okay), french (poorly), german (poorly), basque (poorly)",
    "english (fluently), dutch (okay), spanish (okay), japanese (poorly)",
    "english (fluently), spanish (poorly), hebrew (poorly), german (poorly), russian (poorly)",
    "english (fluently), french (okay), hungarian (poorly), spanish (poorly), german (poorly)",
    "english (poorly), basque (fluently), cebuano (fluently)",
    "english, french, italian (okay), arabic (poorly)",
    "english (fluently), spanish (okay), portuguese (okay), chinese (poorly), russian (poorly)",
    "english, czech (fluently), french (okay)",
    "english, portuguese (poorly), german (poorly), spanish (poorly)",
    "english (fluently), spanish (fluently), italian (okay), japanese (poorly), german (poorly)",
    "english (fluently), c++ (okay), tagalog (poorly)",
    "english (fluently), spanish (poorly), italian (poorly), german (poorly)",
    "english (fluently), russian (poorly), french (poorly), german (poorly), italian (poorly)",
    "english (fluently), spanish (okay), dutch (poorly), japanese (poorly)",
    "english (fluently), c++ (fluently), lisp (okay), spanish (poorly)",
    "english (fluently), tagalog (poorly), french (poorly)",
    "english (fluently), other (fluently), french (poorly), german (poorly)",
    "english (fluently), french (okay), hindi (okay), urdu (okay)",
    "english (fluently), russian (fluently), ukrainian (fluently), spanish (poorly), italian (poorly)",
    "english (fluently), japanese (okay), thai (poorly), french (poorly)",
    "english (fluently), german (fluently), japanese (okay)",
    "english (fluently), hindi (fluently), other (fluently)",
    "english (fluently), spanish (okay), french (poorly), chinese (poorly)",
    "english (fluently), french, latin, german, ancient greek",
    "english, french, irish",
    "english (fluently), greek (poorly), catalan (poorly)",
    "english (fluently), german (fluently), czech (fluently), slovak (fluently), italian (poorly)",
    "english, french (fluently)",
    "english (fluently), chinese (fluently), spanish (poorly), c++",
    "english (fluently), norwegian (fluently), sign language (okay)",
    "english, serbian, french, spanish, german",
    "english (fluently), french (okay), spanish (poorly), turkish (poorly)",
    "english, spanish, english",
    "english (fluently), chinese (okay), spanish (poorly)",
    "english, sign language",
    "english, chinese (poorly)",
    "english (fluently), tagalog (okay)",
    "english (fluently), german (okay), spanish (okay), french (poorly)",
    "english (fluently), russian (okay), spanish (fluently), french (fluently)",
    "english (fluently), bengali (poorly), spanish (poorly)",
    "english, japanese (okay), chinese (poorly), spanish (poorly)",
    "english (fluently), chinese (okay), french (okay), japanese (okay), spanish (okay)",
    "english (fluently), italian (poorly), spanish (poorly), german (poorly)",
    "english (fluently), italian (poorly), spanish (poorly), french (poorly), german (poorly)",
    "english (fluently), chinese (fluently), french (okay), spanish (poorly), japanese (poorly)",
    "english (fluently), chinese (poorly), latin (poorly), spanish (poorly), hindi (poorly)",
    "english (fluently), french (fluently), spanish (okay), italian (okay), hebrew (okay)",
    "english (fluently), tamil (okay), spanish (okay)",
    "english (fluently), chinese (fluently), french (okay)",
    "english (fluently), c++ (okay), latin (poorly), spanish (poorly)",
    "english (fluently), polish (okay), french (okay)",
    "english, spanish, hindi, german, french",
    "english (fluently), dutch (fluently), german (okay), icelandic (poorly)",
    "english (fluently), french (poorly), hindi (fluently)",
    "english (fluently), urdu (okay)",
    "english (fluently), tagalog, japanese",
    "english (fluently), romanian (okay)",
    "english (fluently), italian (fluently), french (fluently)",
    "english (fluently), russian (poorly)",
    "english (fluently), french (fluently), chinese (okay)",
    "english (fluently), spanish (fluently), french (okay), japanese (poorly), italian (poorly)",
    "english (fluently), arabic (okay), chinese (okay)",
    "english (fluently), portuguese (fluently), spanish (poorly)",
    "english, french (fluently), italian (fluently), arabic (poorly)",
    "english, sign language (fluently), french (fluently), italian (okay), thai (okay)",
    "english, maori, bengali, danish",
    "english (fluently), hindi (fluently), tamil (okay)",
    "english (fluently), spanish (okay), korean (okay), italian (poorly), chinese (poorly)",
    "english, russian, spanish",
    "english (poorly), spanish (poorly), french (poorly), chinese (fluently)",
    "english (fluently), spanish (poorly), english (poorly)",
    "english (fluently), italian (fluently), latin (poorly), c++ (okay)",
    "english (fluently), farsi (poorly), french (okay)",
    "english (fluently), icelandic (poorly), spanish (fluently), c++ (fluently)",
    "english, spanish (okay), hebrew (poorly), swahili (poorly)",
    "english, arabic (poorly), french (poorly)",
    "english (fluently), portuguese (okay), spanish (okay)",
    "english (fluently), hungarian (fluently), romanian (fluently), italian (okay), french (okay)",
    "english (fluently), chinese (poorly), tagalog (poorly), c++ (poorly)",
    "english, arabic, urdu, hindi",
    "english, english (fluently), french (fluently)",
    "english, spanish, korean",
    "english (fluently), russian (fluently), spanish (fluently), italian (okay)",
    "english (poorly), ancient greek (fluently), hawaiian (fluently)",
    "english (fluently), french (okay), russian (poorly), hebrew (poorly)",
    "english (poorly), spanish (fluently), catalan (okay)",
    "english, russian (fluently), romanian (fluently)",
    "english (fluently), arabic (fluently), chinese (poorly)",
    "english (fluently), hebrew (poorly), french (poorly)",
    "english (fluently), spanish (fluently), portuguese (fluently), italian (okay)",
    "english (fluently), serbian (fluently), croatian (fluently)",
    "english (fluently), spanish (okay), italian (poorly), farsi (poorly), german (poorly)",
    "english (fluently), chinese (okay), japanese (okay), c++ (okay)",
    "english, italian (fluently), russian (okay), spanish (okay), french (poorly)",
    "english (fluently), russian (fluently), esperanto (fluently)",
    "english, english (fluently), russian (fluently), spanish (okay)",
    "english, spanish (okay), french (okay), turkish (poorly)",
    "english, italian (okay), latin (fluently), lisp (poorly), japanese (okay)",
    "english (fluently), other",
    "english (fluently), c++ (fluently), german (poorly), french (poorly)",
    "english (poorly), c++ (okay)",
    "english (fluently), hebrew (fluently), yiddish (fluently)",
    "english (fluently), russian (okay), thai (poorly)",
    "english (fluently), french, german",
    "english (fluently), spanish (fluently), french (poorly), chinese (poorly)",
    "english (fluently), chechen (fluently), khmer (fluently), urdu (fluently), ancient greek (okay)",
    "english (fluently), german (fluently), persian (fluently), french (okay)",
    "english (fluently), arabic (fluently), french (poorly), spanish (okay)",
    "english (fluently), german (fluently), japanese (okay), spanish (poorly)",
    "english (fluently), sign language (fluently), finnish (okay), esperanto (okay), portuguese (okay)",
    "english (fluently), hindi (fluently), spanish (poorly), c++ (fluently), other (fluently)",
    "english, mongolian",
    "english (fluently), spanish (okay), italian (okay), greek (poorly), sign language (okay)",
    "english (fluently), latin (fluently), spanish (poorly)",
    "english (fluently), french (fluently), spanish (fluently), german (okay), c++ (fluently)",
    "english (fluently), hebrew (fluently), french (okay), spanish (poorly)",
    "english, spanish (okay), portuguese (okay)",
    "english (fluently), spanish (fluently), romanian (fluently)",
    "english (fluently), tagalog (fluently), spanish (poorly), sign language (okay)",
    "english (fluently), sign language (poorly), polish (poorly)",
    "english (fluently), spanish (okay), chinese (poorly), c++ (okay)",
    "english (fluently), spanish (okay), french (poorly), thai (poorly)",
    "english, korean (okay), japanese (poorly), spanish (poorly)",
    "english (fluently), hindi (okay), bengali (okay), french (poorly), japanese (poorly)",
    "english (fluently), german (poorly), japanese (poorly), other (fluently), spanish (fluently)",
    "english (fluently), croatian (fluently), bengali (okay)",
    "english (fluently), afrikaans (poorly)",
    "english (fluently), vietnamese (fluently), japanese (poorly)",
    "english (fluently), spanish, italian",
    "english (poorly), c++ (fluently), lisp (okay), other (okay)",
    "english (fluently), korean (fluently), chinese (poorly)",
    "english (fluently), swedish (fluently)",
    "english (fluently), irish (poorly), c++ (okay)",
    "english (fluently), russian (okay), russian (poorly)",
    "english (fluently), french (okay), hungarian (okay)",
    "english, spanish (okay), other",
    "english (fluently), spanish (okay), russian (poorly), chinese (poorly)",
    "english (okay), portuguese (fluently), italian (okay), spanish (okay)",
    "english (fluently), occitan (fluently), swahili (fluently), tagalog (fluently), c++ (fluently)",
    "english (fluently), french (okay), c++ (fluently), sign language (poorly), other (fluently)",
    "english (fluently), urdu (fluently)",
    "english (fluently), slovak (fluently), german (fluently)",
    "english (fluently), chinese (okay), lisp (fluently), c++ (okay)",
    "english, spanish, czech",
    "english (fluently), german (fluently), norwegian (fluently), c++ (fluently), french (okay)",
    "english (okay), japanese (poorly)",
    "english (fluently), japanese (okay), swedish (poorly), spanish (poorly)",
    "english, portuguese, french, spanish",
    "english (fluently), other (okay)",
    "english (fluently), german (okay), portuguese (poorly)",
    "english (fluently), japanese",
    "english, gujarati (fluently), hindi (poorly), italian (poorly), c++ (okay)",
    "english (fluently), sign language (fluently), french (okay), spanish (okay)",
    "english (fluently), german (poorly), spanish (poorly), italian (poorly)",
    "english (fluently), swedish (okay), other (fluently), danish (poorly)",
    "english (fluently), spanish (fluently), italian (fluently), german (okay), portuguese (poorly)",
    "english, spanish (okay), german (okay), french (poorly)",
    "english (fluently), french (fluently), german (fluently), italian (poorly), spanish (poorly)",
    "english, german (fluently), thai (poorly), french (poorly)",
    "english, french (okay), spanish (okay), norwegian (poorly)",
    "english (fluently), chinese (okay), spanish (poorly), c++ (fluently)",
    "english, tamil, spanish",
    "english (fluently), spanish (okay), german (okay)",
    "english (fluently), c++ (poorly), ancient greek (poorly), latin (poorly)",
    "english (poorly), english (okay), english (fluently), english, english",
    "english (fluently), french (fluently), portuguese (okay)",
    "english (fluently), chinese (okay), korean (poorly), japanese (poorly)",
    "english (fluently), danish (fluently), swedish (okay), norwegian (okay), german (okay)",
    "english (fluently), russian (okay), japanese (poorly), irish (poorly)",
    "english (fluently), romanian (fluently), italian (fluently), spanish (okay), hungarian (poorly)",
    "english (fluently), french (fluently), arabic (fluently), italian (fluently), russian (fluently)",
    "english, yiddish (fluently)",
    "english (fluently), portuguese (fluently), french (fluently), spanish (okay), vietnamese (poorly)",
    "english (fluently), japanese (fluently), spanish (okay), portuguese (poorly), french (poorly)",
    "english (fluently), italian (poorly), spanish (okay), french (poorly)",
    "english, breton, french, spanish",
    "english (fluently), french (poorly), swedish (poorly), c++ (poorly)",
    "english (fluently), spanish (okay), basque (poorly)",
    "english (fluently), german (poorly), greek (poorly)",
    "english, french, arabic",
    "english (fluently), japanese (fluently), portuguese (fluently)",
    "english (fluently), chinese (fluently), german (poorly), c++ (fluently)",
    "english (okay), chinese (poorly), thai",
    "english (fluently), chinese (poorly), spanish (okay)",
    "english, japanese, spanish (poorly)",
    "english (fluently), spanish (okay), korean (okay), chinese (okay), sign language (poorly)",
    "english (fluently), french (fluently), spanish (fluently), german (okay), czech (okay)",
    "english (fluently), afrikaans (fluently), french (poorly), c++ (okay)",
    "english (fluently), afrikaans (okay), other (okay)",
    "english, french, korean (fluently)",
    "english (fluently), japanese (poorly), tamil (okay), spanish (poorly)",
    "english (fluently), russian (okay), spanish (okay), french (poorly)",
    "english (fluently), french (poorly), german (okay), italian (poorly)",
    "english (fluently), hindi (fluently), gujarati (fluently), french (poorly), c++ (fluently)",
    "english (fluently), dutch (poorly), german (okay), french (fluently), spanish (fluently)",
    "english (fluently), german (poorly), spanish (poorly), japanese (poorly)",
    "english (fluently), chinese (okay), french (fluently), khmer (okay), japanese (okay)",
    "english, german (poorly), french (poorly)",
    "english (fluently), spanish (okay), french (okay), farsi (fluently), hebrew (okay)",
    "english, french, swedish, chinese",
    "english (fluently), italian (poorly), french (poorly), spanish (poorly)",
    "english, serbian",
    "english, french, turkish, romanian",
    "english (fluently), hebrew (fluently), hindi (fluently)",
    "english (fluently), irish (fluently)",
    "english (fluently), german (okay), spanish (poorly), yiddish (poorly)",
    "english (fluently), swedish (fluently), persian (fluently), german (okay)",
    "english (fluently), belarusan, gujarati, lisp, russian (fluently)",
    "english (fluently), french (okay), spanish (poorly), c++ (okay)",
    "english (fluently), chinese (okay), yiddish (poorly)",
    "english (fluently), spanish (fluently), chinese (fluently)",
    "english (fluently), dutch (okay), german (okay), spanish (okay)",
    "english (poorly), french (poorly)",
    "english (poorly), german (okay), c++ (okay)",
    "english (okay), german (poorly), spanish (poorly), serbian (poorly)",
    "english, french, sign language",
    "english (poorly), c++ (poorly)",
    "english (fluently), french (okay), spanish (okay), latin (poorly), russian (poorly)",
    "english (okay), french (poorly), spanish (poorly), japanese (poorly)",
    "english, danish",
    "english, french (fluently), arabic (fluently), spanish (okay)",
    "english (fluently), c++ (fluently), bengali (fluently), hindi (fluently)",
    "english (fluently), english (poorly), english (okay)",
    "english (fluently), spanish (fluently), thai (okay)",
    "english (fluently), french (okay), hebrew (okay), spanish (poorly), german (poorly)",
    "english (fluently), french (okay), bulgarian (fluently)",
    "english, french (okay), italian (okay), spanish (okay)",
    "english (fluently), german (fluently), spanish (poorly), italian (poorly)",
    "english (fluently), chinese (okay), spanish (poorly), french (poorly)",
    "english, swahili (poorly)",
    "english (fluently), spanish (poorly), c++ (fluently), lisp (fluently)",
    "english (fluently), spanish (okay), indonesian (poorly), other (okay)",
    "english (fluently), chinese (fluently), danish (fluently), german (fluently), french (okay)",
    "english (fluently), c++ (fluently), french (okay), spanish (okay), lisp (fluently)",
    "english (fluently), polish (fluently), russian (poorly), chinese (poorly)",
    "english (fluently), spanish (okay), swahili (poorly)",
    "english (fluently), bengali (fluently), hindi (fluently), spanish (poorly)",
    "english (fluently), latin (poorly), italian (poorly)",
    "english, spanish (okay), chinese (okay), other (poorly)",
    "english, italian, spanish (poorly)",
    "english (fluently), georgian (poorly), spanish (okay)",
    "english (fluently), german (okay), spanish (okay), danish (poorly)",
    "english (fluently), spanish (fluently), chinese (okay)",
    "english, german (fluently), sign language (fluently)",
    "english, english (poorly)",
    "english, french, portuguese (okay), arabic (okay)",
    "english (fluently), french (poorly), greek (poorly)",
    "english (okay), japanese (poorly), afrikaans (poorly), sanskrit (okay)",
    "english (fluently), russian (fluently), other (okay)",
    "english, hebrew, russian, spanish",
    "english (fluently), sign language (fluently), german (fluently), chinese (okay)",
    "english (fluently), italian (okay), korean (poorly), tagalog (poorly)",
    "english (fluently), french (fluently), spanish (okay), chinese (okay)",
    "english (fluently), chinese (okay), dutch (poorly)",
    "english (fluently), russian",
    "english (fluently), portuguese (okay), spanish (fluently), hebrew (okay)",
    "english (fluently), hebrew (okay), sign language (poorly)",
    "english (fluently), khmer (poorly), japanese (poorly)",
    "english (fluently), turkish (fluently), german (fluently), spanish (poorly), hindi (poorly)",
    "english (poorly), afrikaans (fluently), czech (fluently), hawaiian (fluently), ilongo (okay)",
    "english (fluently), japanese (poorly), thai (poorly)",
    "english (fluently), turkish (poorly), farsi (okay)",
    "english, spanish (okay), french (poorly), italian (poorly)",
    "english (fluently), vietnamese (fluently)",
    "english, french (poorly), c++ (poorly)",
    "english, korean (poorly), spanish (okay), german (poorly), other (fluently)",
    "english (fluently), french (fluently), korean (poorly), german (poorly)",
    "english, spanish, italian",
    "english (fluently), chinese (fluently), c++ (okay), thai (okay), ancient greek (poorly)",
    "english (poorly), spanish (poorly), sign language (poorly), lisp (fluently), other (fluently)",
    "english, spanish (fluently), hebrew (fluently)",
    "english, french (okay), sign language (poorly)",
    "english (fluently), german (poorly), spanish (poorly), french (poorly), japanese (poorly)",
    "english (fluently), italian (okay), japanese (poorly), welsh (poorly), french (poorly)",
    "english (fluently), french (fluently), russian (fluently)",
    "english, italian, french (poorly), dutch (poorly), japanese (poorly)",
    "english, vietnamese (fluently), french (poorly)",
    "english (fluently), chinese (okay), swedish (poorly)",
    "english (fluently), spanish (okay), hindi (okay)",
    "english (poorly), spanish (poorly), portuguese (poorly)",
    "english (fluently), czech, hebrew, german, slovak",
    "english (fluently), german (poorly), portuguese (poorly)",
    "english, german (poorly), russian (poorly)",
    "english (fluently), other (fluently), thai (poorly)",
    "english (fluently), afrikaans (fluently), albanian (fluently), arabic (fluently), c++ (fluently)",
    "english (fluently), greek (fluently), russian (okay), spanish (okay), italian (poorly)",
    "english (fluently), french (poorly), italian (okay), afrikaans (poorly), spanish (okay)",
    "english (fluently), serbian (okay), turkish (poorly), german (fluently), spanish (okay)",
    "english (fluently), german (okay), chinese (okay)",
    "english (fluently), spanish (okay), french (okay), swahili (poorly)",
    "english (okay)",
    "english, german (okay), spanish (poorly)",
    "english (fluently), finnish (poorly)",
    "english (fluently), chinese (poorly), spanish (fluently)",
    "english (fluently), spanish (okay), c++ (fluently), japanese (poorly), french (poorly)",
    "english (fluently), chinese (fluently), italian (okay)",
    "english (okay), german (poorly), rotuman (fluently), welsh (fluently), c++ (poorly)",
    "english (fluently), farsi (fluently), persian (fluently), spanish (poorly)",
    "english (fluently), chinese (okay), japanese (poorly)",
    "english (fluently), french (okay), german (okay), latin (poorly), other (okay)",
    "english (fluently), german (okay), chinese (poorly), french (poorly)",
    "english (fluently), spanish (okay), sign language (okay), french (poorly)",
    "english, latin (okay), japanese (okay), c++ (fluently), other",
    "english (fluently), french (okay), german (okay), russian (poorly), spanish (poorly)",
    "english (fluently), swahili (okay), spanish (poorly)",
    "english (fluently), vietnamese (okay), chinese (okay)",
    "english (fluently), ancient greek (poorly), latin (poorly), spanish (okay)",
    "english (fluently), spanish (okay), tagalog (fluently), cebuano (fluently), hawaiian (poorly)",
    "english, spanish (fluently), sign language (okay)",
    "english (fluently), spanish (fluently), vietnamese (okay)",
    "english (fluently), spanish (okay), hebrew (fluently)",
    "english (fluently), spanish (okay), japanese (poorly), c++ (okay)",
    "english (fluently), swedish (poorly)",
    "english (fluently), tamil (fluently), spanish (okay)",
    "english, german (poorly), french (poorly), spanish (poorly)",
    "english (fluently), latin (poorly), spanish (poorly), sign language (okay)",
    "english (fluently), spanish (poorly), japanese (okay), sign language (poorly)",
    "english (fluently), italian (fluently), spanish (okay), slovenian (poorly)",
    "english, thai, other",
    "english, french (fluently), german (poorly), spanish (poorly)",
    "english (fluently), spanish (fluently), japanese (poorly), italian (poorly)",
    "english (fluently), spanish, french",
    "english (fluently), french (fluently), greek (fluently), german (okay), italian (poorly)",
    "english, russian, sign language",
    "english (fluently), spanish (fluently), other (okay), other, other",
    "english, tamil (okay)",
    "english (fluently), japanese (fluently), russian (poorly), spanish (poorly), other (fluently)",
    "english (fluently), spanish (fluently), russian (okay), french (poorly)",
    "english (fluently), spanish (okay), portuguese (poorly), other (fluently)",
    "english (fluently), french (okay), spanish (okay), italian (okay), japanese (poorly)",
    "english (fluently), hungarian (fluently), spanish (poorly)",
    "english (fluently), c++ (okay), german (poorly), japanese (poorly)",
    "english (fluently), tagalog (poorly), french (poorly), lisp (okay)",
    "english (fluently), korean (okay), french (poorly), latin (poorly)",
    "english (poorly), afrikaans (fluently), dutch (fluently), frisian (okay), yiddish (okay)",
    "english (fluently), french (fluently), chinese (fluently), spanish (poorly)",
    "english (okay), italian (poorly), portuguese (poorly), spanish (fluently)",
    "english (fluently), chinese (fluently), spanish (poorly), vietnamese (okay)",
    "english (fluently), italian (okay), lisp (okay), c++ (okay)",
    "english (fluently), chinese (poorly), german (poorly), spanish (poorly), sign language (okay)",
    "english (okay), french (fluently), german (fluently)",
    "english (fluently), german (okay), latin (poorly), japanese (poorly), c++ (poorly)",
    "english (fluently), spanish (fluently), german (poorly), french (okay)",
    "english, serbian, croatian",
    "english (fluently), thai (fluently), german (poorly)",
    "english (fluently), chinese (fluently), spanish (poorly), korean (poorly)",
    "english (fluently), chinese (poorly), latin (poorly)",
    "english (fluently), dutch (poorly), irish (okay)",
    "english (fluently), spanish (poorly), yiddish (okay)",
    "english (fluently), german (poorly), vietnamese (poorly)",
    "english (fluently), tagalog (fluently), thai (poorly)",
    "english (fluently), chinese (okay), hindi (okay), french (okay)",
    "english (fluently), french (okay), spanish (poorly), dutch (poorly)",
    "english (fluently), chinese (poorly), spanish (poorly), japanese (poorly)",
    "english (fluently), korean (okay), spanish (poorly)",
    "english (poorly), japanese (fluently)",
    "english (fluently), french (fluently), spanish (okay), arabic (poorly)",
    "english, chinese (okay), japanese (poorly), spanish (poorly)",
    "english (fluently), afrikaans (fluently)",
    "english, chinese (okay), spanish (okay), c++ (okay)",
    "english (okay), indonesian (fluently), chinese (poorly), french (poorly)",
    "english (fluently), sign language (poorly), spanish (poorly), french (poorly), basque (poorly)",
    "english (fluently), french (poorly), irish (okay), ancient greek (poorly), latin (poorly)",
    "english (fluently), german (fluently), swedish (okay)",
    "english (fluently), spanish (fluently), french (okay), ancient greek (okay)",
    "english (fluently), french (poorly), german (poorly), italian (poorly), latin (poorly)",
    "english (fluently), vietnamese (fluently), chinese (okay), french (okay)",
    "english (fluently), hindi (okay), other (fluently)",
    "english (fluently), german (fluently), arabic (poorly), hindi (fluently), tamil (okay)",
    "english, swahili (fluently), spanish (poorly)",
    "english, spanish (fluently), icelandic (poorly)",
    "english (fluently), sign language (okay), korean (poorly)",
    "english (poorly), russian",
    "english (fluently), french (fluently), italian (poorly), spanish (poorly)",
    "english (okay), czech (fluently)",
    "english, korean (poorly)",
    "english (fluently), italian (fluently), russian (fluently), hungarian (fluently), french (poorly)",
    "english (fluently), french (okay), c++ (okay), german (poorly)",
    "english (fluently), c++ (okay), other (okay)",
    "english, yiddish (poorly), c++ (poorly)",
    "english (fluently), spanish (poorly), german (poorly), c++ (poorly)",
    "english, c++ (okay), german (okay)",
    "english (poorly), french (poorly), spanish (poorly), sign language (okay)",
    "english, japanese (okay), c++ (fluently)",
    "english, french, arabic, spanish (okay)",
    "english (fluently), french (fluently), german (poorly), japanese (poorly), urdu (poorly)",
    "english (fluently), spanish (poorly), italian (poorly), sign language (poorly)",
    "english (fluently), japanese (fluently), korean (poorly), c++ (poorly)",
    "english (fluently), arabic (poorly), spanish (okay)",
    "english (fluently), spanish (fluently), sign language (poorly), french (poorly)",
    "english (fluently), german (poorly), sign language (fluently), spanish (poorly)",
    "english (fluently), icelandic (okay), thai (okay)",
    "english (fluently), french (fluently), spanish (poorly), hebrew (poorly)",
    "english (fluently), japanese (poorly), spanish (poorly), tagalog (fluently)",
    "english (fluently), chinese, arabic, sign language, afrikaans",
    "english (fluently), spanish (okay), german (poorly), latin (poorly), ancient greek (poorly)",
    "english, portuguese, spanish (okay)",
    "english (fluently), spanish (fluently), esperanto (poorly)",
    "english (okay), tamil (fluently), chinese (fluently), hebrew (okay), tagalog (fluently)",
    "english (fluently), esperanto (poorly), spanish (poorly), portuguese (poorly)",
    "english, c++",
    "english (fluently), hindi (fluently), russian (poorly)",
    "english, cebuano (okay), french (poorly), spanish (poorly), tagalog (okay)",
    "english (fluently), english (okay), english (poorly), spanish (poorly)",
    "english (okay), tagalog (fluently), japanese (poorly)",
    "english (fluently), german (poorly), italian (poorly)",
    "english (fluently), c++ (fluently), french (poorly), lisp (okay)",
    "english, hindi, c++",
    "english, spanish (okay), other (poorly)",
    "english (fluently), arabic (poorly), french (okay), german (poorly)",
    "english (fluently), french (okay), spanish (poorly), thai (poorly)",
    "english, hebrew (fluently), spanish (poorly)",
    "english, french (okay), russian (poorly), german (okay)",
    "english (fluently), french (poorly), c++ (fluently), spanish (poorly)",
    "english (fluently), hawaiian (poorly), french (poorly), portuguese (poorly)",
    "english, chinese, spanish",
    "english (fluently), spanish (okay), sign language (poorly), japanese (poorly), arabic (poorly)",
    "english (fluently), dutch (fluently), spanish (okay)",
    "english (okay), romanian (okay), russian (okay)",
    "english (fluently), tagalog (okay), spanish (okay), japanese (okay)",
    "english (fluently), french (okay), spanish (poorly), italian (okay)",
    "english (fluently), hindi (okay), other",
    "english (fluently), sign language (okay), japanese (poorly)",
    "english (fluently), thai (fluently), hindi (poorly)",
    "english (okay), german (poorly), turkish (fluently), spanish (poorly)",
    "english (fluently), chinese (fluently), french (okay), spanish (poorly)",
    "english (fluently), chinese (poorly), french (poorly), c++ (fluently)",
    "english (fluently), german (fluently), dutch (okay), french (poorly), spanish (poorly)",
    "english (fluently), tibetan, hindi, chinese (okay)",
    "english (fluently), norwegian (fluently)",
    "english (fluently), french (fluently), malay (fluently), german (okay), spanish (poorly)",
    "english, chinese, french",
    "english (fluently), arabic (poorly), french (okay)",
    "english (fluently), korean (poorly), german (poorly), spanish (poorly)",
    "english (fluently), spanish (poorly), chinese (poorly), japanese (poorly), tagalog (poorly)",
    "english (fluently), hawaiian (okay), ancient greek (fluently), spanish (okay), chinese (poorly)",
    "english (fluently), spanish (poorly), greek (poorly), japanese (poorly)",
    "english (okay), tagalog (okay)",
    "english (fluently), hebrew (fluently), spanish (poorly)",
    "english, french (fluently), greek (poorly), spanish (poorly)",
    "english (fluently), turkish (poorly)",
    "english (fluently), russian (poorly), spanish (poorly)",
    "english (fluently), hindi (okay), french (fluently), german (okay), spanish (okay)",
    "english (fluently), spanish (fluently), french (fluently), italian (poorly), c++ (fluently)",
    "english (fluently), sign language (okay), hindi (fluently)",
    "english (fluently), spanish (poorly), german (poorly), latin (poorly)",
    "english, french (okay), portuguese (okay), spanish (poorly)",
    "english, spanish, chinese, c++",
    "english (fluently), spanish (fluently), italian (fluently)",
    "english, french (fluently), chinese (okay)",
    "english (fluently), french (poorly), chinese (okay)",
    "english (fluently), dutch (fluently), spanish (okay), other (fluently)",
    "english (fluently), farsi (fluently), spanish (okay), afrikaans (poorly)",
    "english (fluently), arabic (poorly), german (poorly)",
    "english (fluently), french (poorly), danish (poorly)",
    "english (fluently), chinese (okay), french (poorly), thai (poorly)",
    "english, english (fluently), tagalog (okay), japanese (okay), spanish (poorly)",
    "english (fluently), french (okay), turkish (poorly)",
    "english (fluently), french (okay), spanish (poorly), german (poorly), italian (poorly)",
    "english (fluently), french (fluently), dutch (poorly)",
    "english (fluently), spanish (okay), french (poorly), greek (poorly)",
    "english (fluently), spanish (okay), tagalog (fluently)",
    "english (okay), hebrew (fluently)",
    "english (fluently), spanish (fluently), french (fluently), italian (okay), japanese (poorly)",
    "english (fluently), german (okay), french (poorly), serbian (poorly), spanish (poorly)",
    "english, portuguese, spanish",
    "english (fluently), korean (fluently), french (poorly)",
    "english (fluently), chinese (poorly), spanish (poorly), c++ (okay)",
    "english (fluently), spanish (fluently), german (okay), french (poorly)",
    "english, japanese (poorly), hindi (fluently), spanish (okay), c++ (fluently)",
    "english, portuguese (fluently), korean (poorly), spanish (okay)",
    "english (okay), italian (okay), portuguese (okay), spanish (okay)",
    "english (fluently), french (fluently), dutch (okay), german (poorly), japanese (poorly)",
    "english (fluently), spanish (okay), hindi (poorly), lisp (poorly)",
    "english (fluently), c++ (okay), french (fluently), japanese (okay)",
    "english (fluently), english (okay)",
    "english (okay), russian (poorly)",
    "english (fluently), estonian (poorly), finnish (poorly), french (poorly)",
    "english (fluently), hebrew (fluently), italian (fluently), farsi (okay)",
    "english (fluently), vietnamese (fluently), german (poorly)",
    "english, english (fluently), italian (okay), german (poorly), turkish (fluently)",
    "english (fluently), spanish (fluently), japanese (poorly), french (poorly), russian (poorly)",
    "english (fluently), japanese (fluently), chinese (poorly), korean (okay)",
    "english (fluently), spanish (poorly), japanese (poorly), latin (okay), ancient greek (poorly)",
    "english (okay), french (poorly), spanish (poorly), tagalog (poorly)",
    "english (fluently), korean (fluently), arabic (poorly), french (poorly), spanish (okay)",
    "english, spanish, german, latin",
    "english (fluently), spanish (okay), french (okay), italian (poorly)",
    "english (fluently), italian (fluently), esperanto (poorly)",
    "english (fluently), french (okay), german (okay), arabic (poorly)",
    "english (fluently), turkish (fluently), french (okay)",
    "english (fluently), french (fluently), german (fluently)",
    "english (fluently), french (fluently), italian (fluently), spanish (okay), hindi (okay)",
    "english (fluently), hebrew (okay), italian (okay), spanish (okay), arabic (okay)",
    "english (fluently), other (fluently), c++ (okay)",
    "english (fluently), hebrew (fluently), spanish (okay)",
    "english, spanish, tagalog, hebrew, yiddish",
    "english (fluently), spanish (fluently), french (okay), chinese (poorly)",
    "english (fluently), russian (poorly), spanish (poorly), c++ (fluently)",
    "english (fluently), japanese (okay), spanish (okay), sign language (poorly)",
    "english (fluently), french (okay), spanish (okay), swahili (okay)",
    "english (fluently), italian (fluently), chinese (okay), french (poorly), spanish (poorly)",
    "english (fluently), spanish (fluently), japanese (poorly), italian (okay)",
    "english (fluently), german (fluently), italian (fluently)",
    "english, c++ (poorly), spanish (okay)",
    "english, french, persian",
    "english, french (fluently), german (okay)",
    "english (fluently), japanese (okay), italian (okay), c++ (poorly), french (okay)",
    "english (fluently), arabic (fluently), spanish (okay)",
    "english (fluently), japanese (fluently), korean (okay), french (poorly), spanish (poorly)",
    "english (fluently), tagalog (poorly), spanish (poorly), portuguese (poorly)",
    "english, swahili (okay), hebrew (okay), sign language (okay), spanish (okay)",
    "english, hebrew (poorly), japanese (okay), c++ (fluently)",
    "english, german (okay), danish (poorly)",
    "english (fluently), portuguese (okay), french (poorly), spanish (okay)",
    "english (okay), spanish (poorly), german (poorly)",
    "english (fluently), spanish (fluently), french (poorly), german (poorly), japanese (okay)",
    "english (fluently), spanish (okay), russian (okay), chinese (poorly), czech (poorly)",
    "english, georgian",
    "english (fluently), french (okay), spanish (poorly), bulgarian (okay)",
    "english (fluently), french (okay), yiddish (poorly)",
    "english, spanish (fluently), portuguese (okay), turkish (poorly)",
    "english (fluently), german (fluently), italian (okay), swedish (poorly)",
    "english (fluently), hebrew (poorly), c++ (fluently)",
    "english (fluently), yiddish (poorly)",
    "english, german (poorly), vietnamese (poorly)",
    "english, spanish (poorly), hebrew (fluently)",
    "english (fluently), czech (okay), spanish (poorly)",
    "english (fluently), french (okay), swedish (okay), norwegian (poorly)",
    "english, english, spanish (poorly)",
    "english (fluently), spanish (fluently), german (poorly), french (poorly)",
    "english (fluently), french (okay), hawaiian (okay), hebrew (okay), portuguese (okay)",
    "english (fluently), spanish (okay), chinese (poorly), vietnamese (poorly), indonesian (poorly)",
    "english (fluently), spanish (poorly), french (poorly), portuguese (poorly), german (poorly)",
    "english (fluently), spanish (fluently), french (okay)",
    "english, tagalog (fluently), german, spanish",
    "english (fluently), danish",
    "english, thai (okay), other (okay), spanish (poorly)",
    "english, french, italian",
    "english (fluently), czech (fluently), russian (okay), slovak (fluently), french (poorly)",
    "english (fluently), japanese (okay), german (okay)",
    "english (fluently), spanish (okay), french (poorly), german (poorly)",
    "english, danish, spanish",
    "english (fluently), korean (poorly), spanish (poorly), lisp (fluently)",
    "english (fluently), portuguese (okay), arabic (fluently)",
    "english (fluently), french (okay), italian (okay), german (poorly)",
    "english (fluently), chinese (okay), sign language (okay), spanish (poorly)",
    "english (fluently), c++ (fluently), hebrew (okay), spanish (okay)",
    "english (fluently), hebrew (fluently), c++ (fluently), lisp (poorly)",
    "english, french, polish, spanish, german (poorly)",
    "english (fluently), mongolian (poorly)",
    "english (fluently), latin (poorly), italian (okay)",
    "english (fluently), french (poorly), spanish (poorly), farsi (poorly)",
    "english, farsi, hindi, russian, urdu",
    "english (fluently), french (okay), spanish (poorly), other, other",
    "english (fluently), c++ (okay), indonesian (poorly)",
    "english (fluently), hebrew (okay)",
    "english (fluently), spanish (fluently), french (poorly), c++",
    "english, french, arabic, italian, spanish",
    "english (fluently), russian (okay), lisp (poorly)",
    "english, spanish (okay), sign language (okay)",
    "english (fluently), other (fluently), c++ (fluently), chinese (poorly)",
    "english, french, german, chinese",
    "english (fluently), arabic (okay), tagalog (okay), french (okay), spanish (poorly)",
    "english (fluently), spanish (okay), german (poorly), portuguese (poorly)",
    "english (fluently), tagalog (fluently), spanish (okay), other (fluently)",
    "english (fluently), chinese (okay), indonesian (poorly)",
    "english, german (okay), hindi (poorly), swahili (poorly)",
    "english (fluently), italian (fluently), spanish (okay), french (poorly)",
    "english (fluently), czech (poorly), spanish (okay), italian (okay), german (okay)",
    "english, chinese, korean (poorly), sign language (poorly)",
    "english (fluently), chinese (okay), spanish (okay), danish (poorly)",
    "english (fluently), hebrew (fluently), spanish (okay), italian (poorly), yiddish (okay)",
    "english (fluently), spanish (fluently), french (okay), tagalog (okay)",
    "english, c++, japanese (poorly)",
    "english (fluently), spanish (fluently), other (fluently)",
    "english (fluently), sign language (fluently), spanish (poorly), french (poorly)",
    "english (fluently), c++ (fluently), afrikaans (poorly), japanese (poorly)",
    "english (fluently), french (poorly), spanish (okay), tagalog (okay)",
    "english (fluently), italian (fluently), french (okay), ukrainian (okay), spanish (poorly)",
    "english (fluently), irish (poorly), german (poorly), spanish (poorly)",
    "english (okay), thai (poorly)",
    "english, portuguese (fluently), spanish (okay), french (okay), danish (poorly)",
    "english (okay), french (fluently), spanish (fluently), italian (fluently), japanese (poorly)",
    "english (fluently), spanish (poorly), lisp (poorly), c++ (okay)",
    "english (fluently), hebrew (fluently), russian (okay)",
    "english, french, spanish, italian, german",
    "english (fluently), polish (fluently), french (okay)",
    "english (fluently), chinese (fluently), french (okay), japanese (poorly), portuguese (poorly)",
    "english (okay), spanish",
    "english, czech (fluently), german (poorly), russian (poorly)",
    "english (fluently), c++ (poorly), yiddish (poorly)",
    "english (fluently), c++ (okay), ancient greek (fluently)",
    "english, latin (okay), french (poorly)",
    "english (fluently), spanish (fluently), c++ (fluently)",
    "english (fluently), cebuano (okay), chinese (poorly), japanese (poorly), spanish (poorly)",
    "english, spanish (fluently)",
    "english (poorly), ancient greek, sanskrit, latin, icelandic",
    "english (fluently), hebrew (fluently), spanish (okay), indonesian (poorly)",
    "english (fluently), bengali (okay)",
    "english (fluently), italian (poorly), russian (poorly)",
    "english (fluently), hebrew (fluently), french (fluently), indonesian (poorly), malay (poorly)",
    "english, sign language (fluently), spanish (okay)",
    "english (fluently), c++ (fluently), lisp (poorly), japanese (poorly), spanish (poorly)",
    "english (fluently), french (okay), irish (poorly), greek (poorly), ancient greek (poorly)",
    "english, greek (poorly), german (poorly)",
    "english (fluently), chinese (okay), spanish (okay), sign language (okay)",
    "english (fluently), french (okay), hungarian (poorly), latin (poorly)",
    "english, spanish, german, french, serbian",
    "english (fluently), spanish (fluently), german (okay), portuguese (poorly)",
    "english (fluently), spanish (okay), chinese (poorly), french (okay)",
    "english, spanish (fluently), lisp (okay)",
    "english, hungarian (poorly), spanish (poorly)",
    "english, spanish (poorly), c++ (fluently), lisp (okay)",
    "english (fluently), persian (fluently), spanish (poorly)",
    "english (fluently), japanese (okay), chinese (fluently), c++ (fluently)",
    "english (fluently), dutch (poorly), french (okay), spanish (poorly)",
    "english (fluently), lisp (okay), c++ (okay), german (poorly)",
    "english (fluently), french (poorly), c++ (fluently), lisp (fluently)",
    "english (fluently), french (okay), italian (okay), thai (poorly)",
    "english, german (okay), irish (poorly)",
    "english, french, japanese (poorly), spanish (poorly)",
    "english (fluently), spanish (fluently), italian (poorly), portuguese (poorly), french (poorly)",
    "english (fluently), spanish (okay), polish (poorly), french (poorly)",
    "english, portuguese, japanese",
    "english (fluently), bulgarian (fluently), french (poorly), japanese (poorly), c++ (fluently)",
    "english (fluently), french (poorly), spanish (okay), japanese (poorly)",
    "english (fluently), c++ (fluently), spanish (okay)",
    "english, italian, other, spanish",
    "english, japanese (poorly), chinese (poorly), c++ (okay)",
    "english, swedish (okay), farsi (poorly)",
    "english, spanish (okay), french (okay), persian (poorly)",
    "english (fluently), italian (okay), chinese (poorly), hebrew (poorly)",
    "english, farsi (okay), spanish (okay)",
    "english, serbian (poorly), french (okay), spanish (poorly)",
    "english (fluently), french (fluently), c++ (okay)",
    "english, french (fluently), portuguese (fluently), spanish (okay)",
    "english (poorly), yiddish (fluently), afrikaans (fluently), ancient greek (okay), lisp (poorly)",
    "english (fluently), korean (poorly), italian (poorly), spanish (okay)",
    "english, french (poorly), english (fluently)",
    "english (fluently), spanish (okay), portuguese (poorly), sign language (poorly)",
    "english (fluently), spanish (fluently), french (poorly), portuguese (poorly)",
    "english, greek (poorly), spanish (okay)",
    "english (fluently), french (fluently), hebrew (poorly), russian (poorly)",
    "english (fluently), chinese (fluently), japanese (poorly), german (poorly)",
    "english (okay), italian (poorly), latvian (poorly), spanish (poorly)",
    "english (poorly), french (fluently)",
    "english (okay), spanish (poorly), yiddish (okay)",
    "english, german, turkish",
    "english (fluently), dutch (okay), french (poorly), spanish (poorly)",
    "english (fluently), spanish (fluently), latin (poorly), french (okay), german (poorly)",
    "english, french, hindi, japanese",
    "english, chinese, chinese",
    "english (fluently), hungarian (fluently), german (fluently), spanish (poorly)",
    "english (fluently), ancient greek (poorly), latin (poorly), lisp (poorly)",
    "english (fluently), italian (fluently), spanish (fluently), german (poorly)",
    "english (fluently), chinese (poorly), sign language (poorly)",
    "english (fluently), german (poorly), japanese (poorly), lisp",
    "english (fluently), spanish (okay), c++ (okay), french (poorly), other (fluently)",
    "english (fluently), thai (okay), french (okay), italian (poorly)",
    "english (fluently), spanish (poorly), hebrew (poorly)",
    "english (fluently), chinese (poorly), vietnamese (poorly), japanese (poorly), spanish (okay)",
    "english (okay), indonesian (poorly), spanish (poorly)",
    "english (fluently), chinese (poorly), spanish (poorly), thai (poorly)",
    "english (fluently), hebrew (fluently), romanian (fluently), spanish (fluently), french (okay)",
    "english (fluently), c++ (poorly), chinese (fluently), french (okay), sign language (okay)",
    "english (fluently), spanish (fluently), french (okay), greek (poorly), chinese (poorly)",
    "english (fluently), french (poorly), swahili (okay), spanish (poorly), c++ (poorly)",
    "english (fluently), german (fluently), latin (fluently), french (okay), spanish (poorly)",
    "english (fluently), chinese (fluently), vietnamese (poorly), spanish (okay)",
    "english (fluently), c++ (poorly), other (poorly)",
    "english (fluently), russian (fluently), turkish (fluently)",
    "english (fluently), bengali (fluently), spanish (fluently)",
    "english (okay), spanish (okay), japanese (poorly), c++ (fluently), italian (poorly)",
    "english (fluently), c++ (fluently), other (fluently), spanish (poorly)",
    "english (fluently), dutch (poorly), spanish (okay)",
    "english, russian, french, ukrainian",
    "english (fluently), japanese (poorly), german (okay), spanish (poorly), other (fluently)",
    "english (okay), arabic (okay)",
    "english (fluently), spanish (poorly), finnish (poorly), japanese (fluently)",
    "english (fluently), korean (okay), spanish (okay), portuguese (poorly), c++ (okay)",
    "english (fluently), italian (fluently), spanish (fluently), german (poorly), japanese (poorly)",
    "english (fluently), vietnamese (fluently), spanish (poorly), french (poorly)",
    "english (fluently), spanish (fluently), portuguese (okay), french (okay), other (okay)",
    "english (fluently), spanish (poorly), greek (poorly), arabic",
    "english (okay), chinese (poorly), c++ (okay)",
    "english (fluently), french (okay), italian (fluently), spanish (fluently)",
    "english (fluently), spanish (okay), latin (poorly), italian (poorly)",
    "english (fluently), latvian (poorly)",
    "english (fluently), spanish (okay), russian (poorly)",
    "english (fluently), spanish (poorly), french (poorly), italian (poorly)",
    "english (fluently), hebrew (fluently), russian (fluently), french (okay), spanish (poorly)",
    "english (fluently), french (poorly), chinese (poorly), other (fluently)",
    "english (fluently), korean (fluently), japanese (okay)",
    "english (okay), c++ (okay), spanish (poorly), icelandic (poorly)",
    "english (fluently), c++ (fluently), farsi (fluently)",
    "english (fluently), khmer (fluently), spanish (poorly)",
    "english (fluently), tagalog (okay), spanish (poorly), italian (poorly), other",
    "english (fluently), lisp (fluently), c++ (poorly)",
    "english (fluently), spanish (poorly)",
    "english (okay), german (poorly)",
    "english, spanish (okay), french (poorly), italian (poorly), portuguese (poorly)",
    "english, spanish (fluently), french (okay), portuguese (okay), other (poorly)",
    "english, maori (fluently), french (okay)",
    "english (fluently), french (poorly), german (okay), italian (okay), spanish (okay)",
    "english (fluently), spanish (okay), russian (okay), hindi (poorly), hebrew (poorly)",
    "english (poorly), spanish (fluently), sign language (okay)",
    "english (fluently), spanish (okay), french (okay)",
    "english (fluently), chinese (fluently), french (okay), spanish (okay)",
    "english (fluently), c++ (okay), french (fluently), german (poorly)",
    "english (fluently), german (fluently), spanish (fluently), french (poorly)",
    "english (fluently), hindi (fluently), bengali (okay)",
    "english, catalan (okay), italian (fluently), spanish (fluently), sign language (okay)",
    "english (fluently), italian (okay), portuguese (poorly), spanish (poorly)",
    "english (fluently), sign language (poorly), c++ (fluently), german (poorly)",
    "english (fluently), bulgarian (fluently), c++ (okay)",
    "english (fluently), latin (poorly), c++ (poorly), german (poorly), spanish (poorly)",
    "english (fluently), french (okay), spanish (poorly), hebrew (poorly)",
    "english (fluently), lisp (okay), c++ (fluently), latin (poorly)",
    "english, german, swedish, danish, turkish (poorly)",
    "english (fluently), spanish (poorly), german (okay)",
    "english (fluently), french (okay), c++, esperanto (poorly), sign language",
    "english (fluently), spanish (poorly), french (poorly), japanese (poorly), c++ (poorly)",
    "english (fluently), german (okay), spanish (okay), japanese (okay)",
    "english (fluently), c++ (fluently), japanese (poorly)",
    "english (fluently), french (fluently), hindi (fluently), urdu (okay)",
    "english (fluently), c++ (poorly), german (fluently), khmer (fluently), mongolian (fluently)",
    "english (fluently), tagalog (okay), japanese (okay), italian (okay)",
    "english (fluently), hungarian (okay), russian (poorly)",
    "english (fluently), japanese (okay), spanish (okay), korean (poorly)",
    "english (fluently), c++ (fluently), french (poorly), lisp (okay), sign language (okay)",
    "english (fluently), c++ (okay), chinese (poorly), spanish (poorly), farsi (poorly)",
    "english (fluently), irish (okay), german (poorly)",
    "english (poorly), french (okay), spanish (poorly), swahili (poorly), occitan (poorly)",
    "english (fluently), latin (okay), esperanto (poorly)",
    "english, chinese (okay), c++ (okay)",
    "english (fluently), french (okay), spanish (poorly), c++ (poorly)",
    "english (fluently), french (okay), russian (poorly), c++ (fluently)",
    "english (fluently), spanish (poorly), tagalog (poorly)",
    "english (fluently), tagalog, spanish (poorly)",
    "english, italian (fluently), sign language (fluently)",
    "english, russian (fluently), spanish (okay), french (okay)",
    "english, french (poorly), hindi (poorly)",
    "english (fluently), italian (poorly), tagalog (poorly)",
    "english (fluently), urdu (fluently), farsi (fluently), hindi (fluently)",
    "english (fluently), spanish (okay), sanskrit (poorly), c++ (poorly)",
    "english, swedish (okay)",
    "english (fluently), italian (fluently), german (okay), spanish (fluently)",
    "english (fluently), korean (fluently), german (poorly), japanese (poorly)",
    "english (okay), german (fluently)",
    "english, english (okay), spanish (fluently), french (poorly)",
    "english (fluently), c++ (okay), lisp (okay), sign language (poorly), other (fluently)",
    "english, irish (poorly)",
    "english (fluently), c++ (fluently), japanese (okay), spanish (okay), romanian (okay)",
    "english (fluently), spanish (okay), chinese (fluently)",
    "english, spanish, french (poorly)",
    "english (fluently), french (fluently), spanish (fluently), german (okay)",
    "english, russian (fluently), ukrainian (okay)",
    "english (fluently), sign language (poorly)",
    "english (fluently), chinese (fluently), spanish (poorly), italian (okay)",
    "english (fluently), french (fluently), spanish (okay)",
    "english (fluently), polish (poorly), c++ (fluently)",
    "english (fluently), spanish (fluently), french (okay), other (okay)",
    "english (fluently), italian (okay), german (poorly), portuguese (okay), hebrew (poorly)",
    "english (fluently), french (okay), german (okay), chinese (okay), spanish (okay)",
    "english (fluently), hindi (fluently), french (fluently), german (okay)",
    "english (fluently), farsi (fluently), urdu (okay), other (fluently)",
    "english (fluently), hebrew (okay), french (okay), spanish (poorly)",
    "english (fluently), german (fluently), spanish (fluently), french (okay)",
    "english (fluently), japanese (okay), sign language (poorly)",
    "english (fluently), norwegian (fluently), german (okay)",
    "english, french (okay)",
    "english, french (okay), spanish (fluently), tagalog (poorly)",
    "english, indonesian (poorly), french (okay), spanish (okay), hindi (poorly)",
    "english, spanish, vietnamese",
    "english, german, spanish, french, other",
    "english (fluently), occitan (poorly)",
    "english (fluently), chinese (poorly), sanskrit, german, c++ (fluently)",
    "english (fluently), chinese (fluently), tagalog (fluently), japanese (poorly)",
    "english (fluently), chinese (fluently), french (poorly), spanish (poorly), c++ (fluently)",
    "english (fluently), khmer (fluently)",
    "english (fluently), spanish (okay), japanese (poorly), c++ (poorly), lisp (poorly)",
    "english (fluently), spanish (fluently), italian (poorly), chinese (poorly)",
    "english (fluently), arabic (poorly), spanish (poorly)",
    "english (fluently), italian",
    "english (fluently), spanish (okay), hebrew (poorly), french (poorly)",
    "english (fluently), polish (fluently), italian (fluently), slovak (okay)",
    "english, hebrew (okay), french (poorly)",
    "english, italian (okay), spanish (okay)",
    "english, german, japanese, spanish",
    "english (poorly), other (fluently)",
    "english (fluently), japanese (okay), swedish (poorly)",
    "english (okay), english (fluently), spanish (okay)",
    "english (okay), dutch (okay), spanish (okay), english (okay), english (okay)",
    "english, arabic (fluently), turkish (okay), french (okay), farsi (poorly)",
    "english, arabic, spanish, chinese, french",
    "english, spanish (okay), french (okay), greek (okay), hebrew (poorly)",
    "english, spanish (okay), sign language (okay), norwegian (poorly)",
    "english (fluently), c++ (fluently), french (poorly)",
    "english (fluently), greek (okay)",
    "english (fluently), french (fluently), spanish (okay), other (fluently)",
    "english, latin (poorly), spanish (poorly)",
    "english, finnish",
    "english (fluently), spanish (okay), french (poorly), farsi (poorly)",
    "english, chinese, german (poorly)",
    "english (fluently), chinese (okay), other (poorly)",
    "english (fluently), french (fluently), german (fluently), other (okay)",
    "english (fluently), french (fluently), greek (poorly)",
    "english (fluently), spanish (fluently), portuguese (fluently), french (okay)",
    "english (fluently), french (okay), swahili (poorly), spanish (poorly)",
    "english (fluently), danish (fluently), italian (poorly), german (poorly), french (poorly)",
    "english (okay), french (okay), german (okay), swedish (okay)",
    "english (fluently), german (fluently), turkish (fluently)",
    "english, czech (okay), spanish (poorly)",
    "english (fluently), chinese (fluently), c++ (okay)",
    "english (fluently), german (poorly), danish (poorly)",
    "english (fluently), russian, chinese",
    "english (fluently), italian (okay), japanese (poorly), c++ (poorly), finnish (poorly)",
    "english, spanish (fluently), portuguese (fluently), french (okay)",
    "english (fluently), spanish (fluently), french (okay), portuguese (poorly)",
    "english, chinese, italian",
    "english (fluently), vietnamese (poorly), japanese (poorly), french (poorly)",
    "english (fluently), chinese (okay), spanish (okay), korean (poorly), japanese (poorly)",
    "english (fluently), french (fluently), sign language (poorly), c++ (poorly)",
    "english, spanish (okay), sign language (poorly), latin (poorly)",
    "english (fluently), chinese (fluently), japanese (poorly), korean (poorly), spanish (poorly)",
    "english (fluently), portuguese (fluently), spanish (okay), french (okay)",
    "english (fluently), c++ (fluently), chinese (poorly)",
    "english (fluently), croatian (fluently), french (poorly)",
    "english (fluently), tamil (fluently), hindi (poorly)",
    "english (fluently), spanish (okay), latin (okay), chinese (poorly)",
    "english (fluently), other (fluently), japanese (poorly)",
    "english (fluently), chinese (poorly), french (poorly)",
    "english (fluently), russian (fluently), italian (poorly), spanish (poorly)",
    "english, english, french, spanish (poorly)",
    "english, swahili (fluently), spanish (okay), chinese (okay)",
    "english (fluently), french (okay), portuguese (fluently), italian (okay), spanish (fluently)",
    "english (fluently), tagalog (poorly), japanese (poorly)",
    "english (fluently), greek (fluently), french (poorly)",
]

relationship_types = [
    "short_term relationship",
    "long_term relationship",
    "make friends"
]

drugs = [
    "often",
    "sometimes",
    "never",
    "nan"
]

texts = [
    "Are you a magician? Because whenever I look at your profile, everyone else disappears.",
    "Do you believe in love at first swipe?",
    "Is your name Google? Because you've got everything I've been searching for.",
    "Excuse me, but I think the stars tonight are outshone by your beauty.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Do you have a map? I keep getting lost in your profile pictures.",
    "I must be a snowflake because I've fallen for you.",
    "Are you a Wi-Fi signal? Because I'm feeling a strong connection.",
    "If beauty were time, you’d be an eternity.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Is your name Wi-fi? Because I'm feeling a connection.",
    "Excuse me, but I think the best part of your profile is the 'send message' button.",
    "If you were a cat, you'd purr-fect.",
    "Are you a camera? Because every time I see your pictures, I smile.",
    "Do you have a sunburn, or are you always this hot?",
    "Are you a time traveler? Because I can't imagine my future without you.",
    "If you were a fruit, you’d be a fineapple.",
    "Do you have a name or can I call you mine?"
]